### ISSUE TITLE
New site blueprint view is broken

### ISSUE THREAD

**Issue by Fryuni** [FactorioBlueprints/factorio-prints#306]
Opening a blueprint the new site gives this error

URL: https://www.factorio.school/view/-LGZibw9_MsTwgweiHDZ
```
react-dom.production.min.js:209 TypeError: Cannot read property 'uid' of undefined
    at yr.render (SingleBlueprint.js:29)
    at Va (react-dom.production.min.js:182)
    at Ba (react-dom.production.min.js:181)
    at Es (react-dom.production.min.js:263)
    at yu (react-dom.production.min.js:246)
    at vu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:239)
    at nu (react-dom.production.min.js:230)
    at qu (react-dom.production.min.js:281)
    at react-dom.production.min.js:284
```

The same id on the old site works fine: https://factorioprints.com/view/-LGZibw9_MsTwgweiHDZ

**Comment by gaston-flores** [comment]
I have the same issue, happens only if you haven't logged in. I opened a PR in #307 should fix it.

**Comment by FactorioBlueprints** [comment]
Thanks for the report. Fixed! Please force refresh.

**Comment by chrisn77** [comment]
Still broken for me.  I get the error (tried in both Chrome and Edge):
================
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
================
This happens on the homepage as well as other saved tabs

**Comment by Fryuni** [comment]
Yeah, now the new site seems to be completely broken. Everything is returning a 503 Service Unavailable. Probably completely unrelated to this issue, some of the heroku config might have changed

**Comment by Fryuni** [comment]
The old sites still works fine.

**Comment by chrisn77** [comment]
fyi - https://www.factorio.school/ is working again now.
